config/routes.rb
Rails.application.routes.draw do

  match '/leaderboard' => 'leaderboards#index', via: [:get, :post]
  

  resources :players

  root to: 'application#index'

  get '/player_two' => 'application#player_two'

  get '/game/socket' => 'games#socket'
  get '/game/start' => 'games#start'
  get '/game/signup' => 'games#signup'
  get '/game/new' => 'games#new'

  namespace :admin do
    resources :questions
  end
  
  get '/admin' => 'admin/base#index'

end

app/models/leaderboard.rb
class Leaderboard < ActiveRecord::Base
  has_many :players

  def redis_key(str)
    "leaderboard:#{self.id}:#{str}"
  end
  
  def top_10_scores
    top_10_score_ids = $redis.zrevrange(self.redis_key('scores'), 0, 10)
    Player.find(top_10_score_ids).sort_by {|score| top_10_score_ids.index(score.id.to_s)}
  end




end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  # before_action :set_leaderboard, only: [:show, :edit, :update, :destroy]
  before_action :reset_leaderboard, only:[:index]

  # GET /leaderboards
  # GET /leaderboards.json

  # def top_10_scores
  #   @leaderboard = LeaderBoard.find(params[:leaderboard_id])
  #   render :partial => 'leaderboards/leaderboard', :locals => {:leaderboard => @leaderboard}
  # end

  def index
    # All of this logic is now happening in a before_action (see end of file)
    respond_to do |format|
      format.html {}
      format.json {}
    end
  end

  # GET /leaderboards/1
  # GET /leaderboards/1.json
  def show
  end

  # GET /leaderboards/new
  def new
    @leaderboard = Leaderboard.new
  end

  # GET /leaderboards/1/edit
  def edit
  end

  # POST /leaderboards
  # POST /leaderboards.json
  def create
    @leaderboard = Leaderboard.new(leaderboard_params)

    respond_to do |format|
      if @leaderboard.save
        format.html { redirect_to @leaderboard, notice: 'Leaderboard was successfully created.' }
        format.json { render :show, status: :created, location: @leaderboard }
      else
        format.html { render :new }
        format.json { render json: @leaderboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leaderboards/1
  # PATCH/PUT /leaderboards/1.json
  def update
    respond_to do |format|
      if @leaderboard.update(leaderboard_params)
        format.html { redirect_to @leaderboard, notice: 'Leaderboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @leaderboard }
      else
        format.html { render :edit }
        format.json { render json: @leaderboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leaderboards/1
  # DELETE /leaderboards/1.json
  def destroy
    @leaderboard.destroy
    respond_to do |format|
      format.html { redirect_to leaderboards_url, notice: 'Leaderboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def reset_leaderboard
      ten=(1..10).to_a
      all_players = Player.all.map { |p| ["#{p.first_name[0]}" + ".#{p.last_name}", p.score] }
      all_players_sorted = all_players.sort {|a,b| b[1] <=> a[1]}
      @top_10 = ten.zip(all_players_sorted)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leaderboard_params
      params.require(:leaderboard).permit(:game, :description, :date)
    end
end

app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
end

app/views/leaderboards/_form.html.haml
= simple_form_for(@leaderboard) do |f|
  = f.error_notification

  .form-inputs
    = f.input :game
    = f.input :description
    = f.input :date

  .form-actions
    = f.button :submit

app/views/leaderboards/_leaderboard.html.haml
%ul
  - @top_10.each do |p|
    %li
      %h1 
        = p[1]
        = p[0]

app/views/leaderboards/edit.html.haml
%h1 Editing leaderboard

= render 'form'

= link_to 'Show', @leaderboard
\|
= link_to 'Back', leaderboards_path

app/views/leaderboards/index-archive.html.haml
.col-md-12.col-sm-12.reset#leaderboard
  .col-sm-3.col-md-2#blue_content.reset
    =image_tag("lb.png", style:"max-height:130px")
    =image_tag("audacy.png", class: "audacy_lb")
    %br/
    %h1.brightest_bulb
      THE 
      %br/ 
      BRIGHTEST 
      %br/ 
      BULBS
    %ul.list-group#top_10_ul
      - @top_10.each do |p|
        %li.list-group-item#top_10_list
          = p[0] 
          = p[1][0]
          = p[1][1]
  .col-sm-9.col-md-10#main_content.reset
    .pregame.reset
      = image_tag "audacy.png", class: "pregame_image"
      = link_to "Let's Play!", "#", id: "moderator_link", class: "btn btn-primary btn-lg moderator_link"
    .col-md-12.container.game.reset
      .col-sm-6.reset
        .countdown
        .scoreboard
          .username_header
            %span.username_span 
        %h1.question_header QUESTION
        .question
      .col-sm-6.reset
        %ul.leaderboard_answers

    .col-md-12.playerboard.reset
      =image_tag("blue_content_horizontal.png", style: "width:100%")
%div.new_session

app/views/leaderboards/index.html.erb
<div class="leaderboard-container group" id="leaderboard">
	<div class="leaderboard-container-aside">
		<div class="logo-container">
			<%= image_tag "Audacy-Logo-lockup.png" %>
		</div>
			<div class="leaderboard-list">
				<ol>
					<% @top_10.each do |p| %>
					<li>
	          <%= p[1][0] %>
	          <%= p[1][1] %>
					</li>
					<% end %>
				</ol>
			</div>
	</div> <!-- leaderboard-container-aside -->
	<div class="new_game">
		<h1 style="padding-bottom:50px">Thanks for Playing!</h1>
		<div class="total-score-text-2">TOTAL POINTS</div>
		<div class='final-count-showdown'>
			<h1 class="player1-center end_score">Player One</h1>
			<div id="total-score-player1-leaderboard">0</div>
		</div>
		<div class='final-count-showdown'>
			<h1 class="player2-center end_score">Player Two</h1>
			<div id="total-score-player2-leaderboard">0</div>
		</div>
	</div>
	<div class="pregame reset">
  	<%= image_tag "audacy.png", class: "pregame_image" %>

		<%= link_to "Let's Play!", "#", id: "moderator_link", class: "btn btn-primary btn-lg moderator_link" %>
  </div>
	<div class="leaderboard-container-section end_of_game">
		<div class="question-container group">
			<div class="question-container-left">
				<h1>Question:</h1>
				<p class="question"></p>
				<div class="timer-container">
					<p class="text-align-center margin-top-50">TIMER</p>
					<div id="progressBar">
  					<div></div>
					</div>


				</div>
			</div>
			<div class="question-container-right">
				
			</div>
			
		</div><!-- question-container -->
		<div class="head-to-head-container group">
			<div class="lightbulb-container-left">
					<div class="single-leaderboard-lightbulb group">
						<figure class="leaderboard-lightbulb-square">A</figure><div class="leaderboard-lightbulb-left-2"></div><p class="leaderboard-lightbulb-left-text-2">-</p>
					</div>
					<div class="single-leaderboard-lightbulb group">
						<figure class="leaderboard-lightbulb-square">B</figure><div class="leaderboard-lightbulb-left-3"></div><p class="leaderboard-lightbulb-left-text-3">-</p>
					</div>
					<div class="single-leaderboard-lightbulb group">
						<figure class="leaderboard-lightbulb-square">C</figure><div class="leaderboard-lightbulb-left-4"></div><p class="leaderboard-lightbulb-left-text-4">-</p>
					</div>
					<div class="single-leaderboard-lightbulb group">
						<figure class="leaderboard-lightbulb-square">D</figure><div class="leaderboard-lightbulb-left-5"></div><p class="leaderboard-lightbulb-left-text-5">-</p>
					</div>
					<div class="single-leaderboard-lightbulb group">
						<figure class="leaderboard-lightbulb-square">E</figure><div class="leaderboard-lightbulb-left leaderboard-lightbulb-left-6"></div><p class="leaderboard-lightbulb-left-text-6">-</p>
					</div>
			</div>
			
			<div class="center-player-display group"> 
				<div class="player1-center">Player One</div>
				<div class="versus dark-text">vs</div> 
				<div class="player2-center">Player Two </div>
			</div>
			
			<div class="lightbulb-container-right">
					<div class="single-leaderboard-lightbulb group">
					<figure class="leaderboard-lightbulb-square">A</figure>
					<div class="leaderboard-lightbulb-right-2"></div>
					<p class="leaderboard-lightbulb-right-text-2">-</p>
					</div>
					
					<div class="single-leaderboard-lightbulb group">
					<figure class="leaderboard-lightbulb-square">B</figure>
					<div class="leaderboard-lightbulb-right-3"></div>
					<p class="leaderboard-lightbulb-right-text-3">-</p>
					</div>
					
					<div class="single-leaderboard-lightbulb group">
					<figure class="leaderboard-lightbulb-square">C</figure>
					<div class="leaderboard-lightbulb-right-4"></div>
					<p class="leaderboard-lightbulb-right-text-4">-</p>
					</div>
					
					<div class="single-leaderboard-lightbulb group">
					<figure class="leaderboard-lightbulb-square">D</figure>
					<div class="leaderboard-lightbulb-right-5"></div>
					<p class="leaderboard-lightbulb-right-text-5">-</p>
					</div>
					
					<div class="single-leaderboard-lightbulb group">
					<figure class="leaderboard-lightbulb-square">E</figure>
					<div class="leaderboard-lightbulb-right-6"></div>
					<p class="leaderboard-lightbulb-right-text-6">-</p>	
					</div>
			</div>
		</div>
		<div class="total-score-container group">
			<div class="total-score-player1">0</div>
			<div class="total-score-text">TOTAL POINTS</div>
			<div class="total-score-player2">0</div>
		</div>
	
	</div><!-- leaderboard-container-section -->

</div> <!-- leaderboard-container group -->

app/views/leaderboards/new.html.haml
%h1 New leaderboard

= render 'form'

= link_to 'Back', leaderboards_path

app/views/leaderboards/show.html.haml
%p#notice= notice

%p
  %b Game:
  = @leaderboard.game
%p
  %b Description:
  = @leaderboard.description
%p
  %b Date:
  = @leaderboard.date

= link_to 'Edit', edit_leaderboard_path(@leaderboard)
\|
= link_to 'Back', leaderboards_path