config/routes.rb
Rails.application.routes.draw do

  match '/leaderboard' => 'leaderboards#index', via: [:get, :post]
  

  resources :players

  root to: 'application#index'

  get '/player_two' => 'application#player_two'

  get '/game/socket' => 'games#socket'
  get '/game/start' => 'games#start'
  get '/game/signup' => 'games#signup'
  get '/game/new' => 'games#new'

  namespace :admin do
    resources :questions
  end
  
  get '/admin' => 'admin/base#index'

end

app/models/question.rb
class Question < ActiveRecord::Base

  def self.random
    offset = rand(Question.count)
    Question.offset(offset).first

    # offset_2 = rand(0...1.0)
    # Question.connection.execute "SELECT setseed(0.2})"
    # Question.order('random()').first
    # http://blog.bigbinary.com/2013/11/13/non-repeating-random-records.html
    # If question_id is the same as current question

  end

  def to_hash
    { id: id,
      question: question,
      answers: [{ answer: answer1, id: 1 },
                { answer: answer2, id: 2 },
                { answer: answer3, id: 3 },
                { answer: answer4, id: 4 }]
    }
  end
end
  

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to [:admin, @question], notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to [:admin, @question], notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to admin_questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def question_params
    params.require(:question).permit(:question, :answer1, :answer2, :answer3, :answer4, :solution)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:answer1, :answer2, :answer3, :answer4, :question, :solution)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/admin/questions/_form.html.haml
= form_for( [:admin, @question] ) do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :question
    = f.text_field :question, size: 50
  .field
    = f.label :answer1
    = f.text_field :answer1, size: 50
  .field
    = f.label :answer2
    = f.text_field :answer2, size: 50
  .field
    = f.label :answer3
    = f.text_field :answer3, size: 50
  .field
    = f.label :answer4
    = f.text_field :answer4, size: 50
  .field
    = f.label :solution
    = f.number_field :solution, in: 1...5
  .actions
    = f.submit 'Save'

app/views/admin/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', [:admin, @question]
\|
= link_to 'Back', admin_questions_path

app/views/admin/questions/index.html.haml
.container
  = link_to 'New Question', new_admin_question_path, :class => "btn-action"

  %h1 Listing questions

  %table
    %thead
      %tr
        %th Question
        %th Answer1
        %th Answer2
        %th Answer3
        %th Answer4
        %th Solution
        %th
        %th
        %th
    %tbody
    - @questions.each do |question|
      %tr
        %td= question.question
        %td= question.answer1
        %td= question.answer2
        %td= question.answer3
        %td= question.answer4
        %td= question.solution
        %td= link_to 'Show', [:admin, question], :class => "btn-default"
        %td= link_to 'Edit', edit_admin_question_path(question), :class => "btn-default"
        %td= link_to 'Destroy', [:admin, question], :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn-default"


  = link_to 'New Question', new_admin_question_path, :class => "btn-action"

app/views/admin/questions/new.html.haml
%h1 New question

= render 'form'

= link_to 'Back', admin_questions_path

app/views/admin/questions/show.html.haml
%p#notice= notice

%p
  %b Question:
  = @question.question
%p
  %b Answer1:
  = @question.answer1
%p
  %b Answer2:
  = @question.answer2
%p
  %b Answer3:
  = @question.answer3
%p
  %b Answer4:
  = @question.answer4
%p
  %b Solution:
  = @question.solution

= link_to 'Edit', edit_admin_question_path(@question)
\|
= link_to 'Back', admin_questions_path